language: cpp
sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew install cmake"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - gcc
            - libboost-dev
            - cmake
          update: true
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y update && sudo apt-get install -y cmake clang; fi
  - git clone --depth 1 https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake .. && cmake --build .
script:
  - ./test_graph
  - ./test_dag

notifications:
  email:
    on_failure: change
    on_success: never
