language: cpp
sudo: required
os: linux

matrix:
  include:
    - env: COMPILER=clang BUILD=Debug
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - clang
            - libboost1.67-all-dev
            - cmake
    - env: COMPILER=clang BUILD=Release
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - clang
            - libboost1.67-all-dev
            - cmake
    - env: COMPILER=g++ BUILD=Debug STANDARD=17
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - libboost1.67-all-dev
            - cmake
    - env: COMPILER=g++ BUILD=Release STANDARD=17
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - libboost1.67-all-dev
            - cmake
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew install cmake boost"
install:
  - git clone --depth 1 https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo -E cmake --build build/ --target install
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake .. && cmake --build .
script:
  - ./test_graph
  - ./test_dag

notifications:
  email:
    on_failure: change
    on_success: never
